"""add avatar to datas table

Revision ID: 88c567b9d8a9
Revises: 1be37b89a923
Create Date: 2025-08-20 21:43:01.777669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c567b9d8a9'
down_revision: Union[str, Sequence[str], None] = '1be37b89a923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datas', sa.Column('avatar', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datas', 'avatar')
    # ### end Alembic commands ###
