"""add avatar and country to user table

Revision ID: 2b3ed9691ff6
Revises: b00c9ce165a7
Create Date: 2025-09-09 14:15:18.033984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3ed9691ff6'
down_revision: Union[str, Sequence[str], None] = 'b00c9ce165a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
