"""update auth db

Revision ID: b00c9ce165a7
Revises: 54c6f76f6ff5
Create Date: 2025-09-05 17:09:09.243143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00c9ce165a7'
down_revision: Union[str, Sequence[str], None] = '54c6f76f6ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_profile_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_usage_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'profile_id')
    op.drop_column('users', 'usage_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usage_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_usage_id_key'), 'users', ['usage_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_profile_id_key'), 'users', ['profile_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
